### ISSUE TITLE
Published Date?

### ISSUE THREAD

**Issue by buffaloDeveloper** [dermasmid/scrapetube#5]
I only see this in the output:

```
'publishedTimeText': {
 		'simpleText': 'Streamed 59 minutes ago'
 	},
```
Is there a way to get a proper date?

**Comment by dermasmid** [comment]
Sadly not, If you need more info from what the library returns you might want to use youtube-dl or something similar, you can still use scrapetube to get the list of videos though.

The reason you cant get a precise date is because the library scrapes the YouTube web app and returns you the data, and the YouTube website uses the relative publish times.
